// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKx2i3D037a1R_FUH4d_bOaxyqSlXy0hk',
    appId: '1:626080289010:web:70b8fd617845d54894006b',
    messagingSenderId: '626080289010',
    projectId: 'mylocks',
    authDomain: 'mylocks.firebaseapp.com',
    storageBucket: 'mylocks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjEgLsgl8f0s2PxW8C1lT_91XLu04D6EM',
    appId: '1:626080289010:android:b737bfd57b8cb6e994006b',
    messagingSenderId: '626080289010',
    projectId: 'mylocks',
    storageBucket: 'mylocks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTgg-CRIc0a_-1Z3shMwAYD_U35le2Kbk',
    appId: '1:626080289010:ios:d2e21e3c6e4aebc494006b',
    messagingSenderId: '626080289010',
    projectId: 'mylocks',
    storageBucket: 'mylocks.firebasestorage.app',
    iosBundleId: 'com.example.appFlutter01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTgg-CRIc0a_-1Z3shMwAYD_U35le2Kbk',
    appId: '1:626080289010:ios:d2e21e3c6e4aebc494006b',
    messagingSenderId: '626080289010',
    projectId: 'mylocks',
    storageBucket: 'mylocks.firebasestorage.app',
    iosBundleId: 'com.example.appFlutter01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKx2i3D037a1R_FUH4d_bOaxyqSlXy0hk',
    appId: '1:626080289010:web:04b71660658f08c494006b',
    messagingSenderId: '626080289010',
    projectId: 'mylocks',
    authDomain: 'mylocks.firebaseapp.com',
    storageBucket: 'mylocks.firebasestorage.app',
  );
}
